server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix:  .html
    mode: HTML5

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ww.demo.entity